# -*- coding: utf-8 -*-
"""Roughwork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fBl45t71j-G9cUXIOT1bfGmL6vzzFDwV
"""

import serial #Serial imported for Serial communication
import time #Required to use delay functions
import pyautogui   #Required to to perform actions
ArduinoSerial = serial.Serial('com15',9600) #Create Serial port object called arduinoSerialData
time.sleep(2) #wait for 2 seconds for the communication to get established
while 1:
    incoming = str (ArduinoSerial.readline()) #read the serial data and print it as line
    print incoming
    
    if 'Play/Pause' in incoming:
        pyautogui.typewrite(['space'], 0.2)
    if 'Rewind' in incoming:
        pyautogui.hotkey('ctrl', 'left')  
    if 'Forward' in incoming:
        pyautogui.hotkey('ctrl', 'right') 
    if 'Volume Incresaed' in incoming:
        pyautogui.hotkey('ctrl', 'down')
        
    if 'Volume Decreased' in incoming:
        pyautogui.hotkey('ctrl', 'up')
    incoming = "";



Project subject and link for the data:
## world Happiness
https://www.kaggle.com/unsdsn/world-happiness?select=2015.csv

### Virus mutation
https://www.kaggle.com/jamzing/sars-coronavirus-accession?select=SARS_CORONAVIRUS_287BP_MN975263.1_accession_nucleotide.csv


### Accomodation
https://www.kaggle.com/kerneler/starter-accomodation-in-india-for-0fd527d4-e

#### Air pollution in India During Covid
https://www.kaggle.com/parulpandey/breathe-india-covid-19-effect-on-pollution/

######## Financial Tweets
https://www.kaggle.com/davidwallach/financial-tweets?select=stockerbot-export.csv

####****** Maharashtra Raw Data:
https://mahasdb.maharashtra.gov.in/rawData.do

####### Indian Medical Facility
https://www.kaggle.com/chekoduadarsh/indian-medical-facility-dataset

#### Social Media Data
http://networkrepository.com/

list1 = list([1, 2, 3])
print(list1)

list1=list()
print(list1)

list1=[]
print(list1)

c=[1,3,2]
print(len(c))

s=[1,2,3,4,5]
print(s[0:])
print(s[:0])
print(s[:2])
print(s[:-2])

zoo=["lion","tiger"]
#print(zoo*2)
zoo.insert(3,"snake")

list1 = ["lion","tiger","snake","zebra","cow"]
list1[1:3] = ["apple", "banana"]
print(list1)

mylist = ["apple", "cherry","banana"]
mylist.append("orange")
print(mylist)

mylist = ["apple", "cherry","banana"]
a = ["orange","kiwi"]
mylist.extend(a)
print(mylist)

mylist = ["apple", "cherry","banana"]
mylist.pop(1)
print(mylist)

mylist = ["apple", "cherry","banana"]
v = []
for x in mylist:
  if "a" in x:
    v.append(x)
print(v)

mylist = ["apple", "cherry","banana"]
c = [x for x in mylist if "a" in x]
print(c)

